import 'package:hive/hive.dart';

part 'location_hive.g.dart'; // This is generated by Hive

@HiveType(typeId: 0)
class LocationDataModel {
  @HiveField(0)
  final double latitude;

  @HiveField(1)
  final double longitude;

  LocationDataModel({
    required this.latitude,
    required this.longitude,
  });
}